In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [3]:
# Create tensoroflow constants

a = tf.constant([[10,20],[30,40]])
b = tf.constant([[50,60],[70,80]])

In [4]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [5]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 60],
       [70, 80]], dtype=int32)>

In [6]:
# basic operations

print(a+2)

tf.Tensor(
[[12 22]
 [32 42]], shape=(2, 2), dtype=int32)


In [7]:
print(b+5)

tf.Tensor(
[[55 65]
 [75 85]], shape=(2, 2), dtype=int32)


In [8]:
print(a*2)

tf.Tensor(
[[20 40]
 [60 80]], shape=(2, 2), dtype=int32)


In [9]:
print(b*2)

tf.Tensor(
[[100 120]
 [140 160]], shape=(2, 2), dtype=int32)


In [10]:
print(a*b)

tf.Tensor(
[[ 500 1200]
 [2100 3200]], shape=(2, 2), dtype=int32)


In [11]:
# To perform element wise multiplication use tf.multiply() method.

mul = tf.multiply(a,b)

In [12]:
mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 500, 1200],
       [2100, 3200]], dtype=int32)>

In [13]:
# dot product

dot_product = tf.matmul(a,b)

In [14]:
dot_product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1900, 2200],
       [4300, 5000]], dtype=int32)>